# Generated by Django 4.1.7 on 2023-03-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=100)),
                ('shoe_price', models.CharField(max_length=100)),
                ('shoe_description', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'shoe',
            },
        ),
    ]
