# Generated by Django 4.1.7 on 2023-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='shoe_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
